import { StyleSheet } from "react-native";

export const main_screen_style = StyleSheet.create({
  text2: {
    position: "absolute",
    fontSize: 24,
    fontWeight: "bold",
    paddingTop: 5,
    left: "5%",
    top: "34%",
  },
  text3: {
    position: "absolute",
    fontSize: 24,
    fontWeight: "bold",
    paddingTop: 5,
    left: "5%",
    top: "77%",
  },
  text4: {
    position: "absolute",
    fontSize: 17,
    fontWeight: "bold",
    paddingTop: 5,
    left: "5%",
    top: "81%",
  },
  text5: {
    position: "absolute",
    fontSize: 17,
    paddingTop: 5,
    left: "10%",
    top: "85%",
  },
  text6: {
    position: "absolute",
    fontSize: 17,
    paddingTop: 5,
    left: "10%",
    top: "88%",
  },
  badge: {
    width: 310,
    height: 290,
    backgroundColor: "white",
    marginBottom: 20,
    marginLeft: 10,
    marginRight: 10,
  },
  picture2: {
    width: 300,
    height: 100,
    marginBottom: 5,
  },
  scrollview: {
    position: "absolute",
    top: "38%",
  },
  text7: {
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 17,
    marginBottom: 5,
  },
  text8: {
    textAlign: "center",
    fontSize: 12,
    marginLeft: 5,
  },
  picture3: {
    width: 20,
    height: 20,
  },
  text9: {
    position: "absolute",
    fontSize: 22,
    fontWeight: "bold",
    paddingTop: 5,
    left: "5%",
    top: "10%",
  },
  text10: {
    position: "absolute",
    fontSize: 16,
    paddingTop: 5,
    left: "5%",
    top: "13%",
  },
  text1: {
    position: "absolute",
    fontSize: 24,
    fontWeight: "bold",
    paddingTop: 5,
    left: "5%",
    top: "20%",
  },
  text11: {
    position: "absolute",
    fontSize: 16,
    fontWeight: "bold",
    paddingTop: 5,
    right: "5%",
    top: "20%",
    color: "#5E9D75",
  },
  picture1: {
    position: "absolute",
    width: 22,
    height: 22,
    top: "10%",
    left: "20%",
  },
  picture4: {
    position: "absolute",
    width: 60,
    height: 60,
    top: "25%",
    left: "10%",
  },
  text12: {
    position: "absolute",
    fontSize: 24,
    fontWeight: "bold",
    paddingTop: 5,
    left: "28%",
    top: "27.5%",
  },
  picture5: {
    position: "absolute",
    width: 15,
    height: 15,
    left: "5%",
    top: "86%",
  },
  picture6: {
    position: "absolute",
    width: 15,
    height: 15,
    left: "5%",
    top: "89%",
  },
});
